name: halodoc
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.15.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  firebase_core: 1.11.0
  firebase_auth: 3.3.5
  social_login_buttons: 1.0.6+2
  google_sign_in: 5.2.3
  get_storage: 2.0.3
  google_fonts: 2.2.0
  http: 0.13.4
  cloud_firestore: 3.1.7
  flutter_staggered_grid_view: 0.6.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

